# Site
name: 'Binary Thoughts'
description: 'i read or write things and put them here. its my excuse for toying around with new ideas and practicing the art of writing'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'https://prabjyot29.github.io/binarythoughts'
disqus: 'demowebsite'
email: 'sudanprabjyot@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Prabjyot Sudan
      site:           http://www.binarythoughts.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "This blog is written by me, for me. If you're reading this and you're not me, Welcome! I didn't write this for you, but wow, this is so awesome that you are reading this and want to read more. You are not me and I am not you but maybe we are similar in some ways"
      email:          sudanprabjyot@gmail.com
      twitter:        https://twitter.com/prabjyotsudan

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]